version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    ports:
      - "8000:80"
  grpcservice:
    build:
      context: .
      dockerfile: Dockerfile-GoServer
    expose:
      - "9091"
  default:
    build:
      context: .
      dockerfile: Dockerfile-Envoy
    ports:
      - "9090:9090"
    links:
      - grpcservice
      - nginx
